sudo: required
language: c
compiler:
  - gcc
  - clang
env:
  - MODE=release
  - MODE=debug
services:
  - docker
before_install:
  - docker pull kamailio/pkg-kamailio-docker:dev-stretch
script: docker run -v $TRAVIS_BUILD_DIR:/code:rw kamailio/pkg-kamailio-docker:dev-stretch /bin/bash -c "cd /code; CC=$CC MODE=$MODE ./test/travis/build_travis.sh"
branches:
  only:
    - '/^vseva/'
